apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: allowed-psps
rules:
  - apiGroups: ['policy']
    resources: ['podsecuritypolicies']
    verbs: ['use']
    resourceNames:
      - gce.privileged

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allowed-psps
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: allowed-psps
subjects:
  - kind: Group
    name: system:serviceaccounts
    apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sudo
  labels:
    app: sudo
    env: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sudo
      env: staging
  template:
    metadata:
      labels:
        app: sudo
        env: staging
    spec:
      containers:
        - name: sudo
          image: jonpulsifer/tflab:sudo
          command: ["tail", "-f", "/dev/null"]
          securityContext:
            allowPrivilegeEscalation: false
