apiVersion: v1
kind: ServiceAccount
metadata:
  name: webapp
  namespace: tflab
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: webapp
  namespace: tflab
rules:
  - apiGroups: ['policy']
    resources: ['podsecuritypolicies']
    verbs:     ['use']
    resourceNames:
    - tflab-webapp
    - gce.privileged
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: webapp
  namespace: tflab
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: webapp
subjects:
- kind: ServiceAccount
  name: webapp
  namespace: tflab
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tflab-namespace-psp
  namespace: tflab
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tflab-psp-cluster-defaults
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts
