apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: tflab
  labels:
    app: webapp
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: webapp

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
  namespace: tflab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      serviceAccountName: webapp
      containers:
      - image: jonpulsifer/tflab:webapp
        name: webapp
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 30
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 30
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: TFLAB_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: TFLAB_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: TFLAB_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: TFLAB_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: TFLAB_POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
