apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tflab-psp-cluster-defaults
rules:
  - apiGroups: ['extensions']
    resources: ['podsecuritypolicies']
    verbs:     ['use']
    resourceNames:
    - tflab-restricted
---
